### ISSUE TITLE
Schedule libraries at the config level

### ISSUE THREAD

**Issue by tiphae** [meisnate12/Plex-Meta-Manager-Wiki#21]
Would it be possible to be able to specify schedules at the library level in the config.yml, similar to how we can do individual collections? For example, set library TV to run weekly(monday,wednesday,friday) and library Movies to run (tuesday,thursday,saturday) or monthly(1).

**Comment by meisnate12** [comment]
please head over and post these on the [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager) GitHub this GitHub is specifically for the wiki
