### ISSUE TITLE
PMM collections based on custom genres entered in plex

### ISSUE THREAD

**Issue by tiphae** [meisnate12/Plex-Meta-Manager-Wiki#22]
I've seen some collections based on sub-genres, which obviously aren't found in Plex. I thought adding one to a movie may create it, so I added genre "pandemic" to a zombie movie and now Plex advanced search allows a "genre is pandemic" query. This does properly filter and display that movie, but PMM still errors out on the collection saying no such genre found in plex_search.

**Comment by meisnate12** [comment]
please head over and post these on the [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager) GitHub this GitHub is specifically for the wiki
